#!/bin/bash
#------------------------------------------------------------------------------------------
# Autor: Alberto Valero Mlynaricova
# Fecha: 16/12/2023
#
# Descripción: Script que instala PowerShell y ejecuta un programa en Python para crear recursos.
#               USO: sudo recurso nombre_recurso grupo
#                    programa    nombre recurso      nombre grupo del dominio
#------------------------------------------------------------------------------------------
# Ejecuta el script de Python
python3 /sbin/nuevo_recurso.py
